format = """
$time$directory\
$fill\
$package\
$dart$deno$elixir$elm$golang$java$kotlin$lua$nodejs$php$python$rust$swift\
$terraform\
$memory_usage\
$aws$gcloud\
$git_branch\
$git_status\
$git_commit\
$git_metrics\
$git_state\
$custom\
$cmd_duration\
$line_break\
$status$shell$character\
"""


scan_timeout = 30
command_timeout = 1500

[character]
success_symbol = " "
error_symbol = "[ ](#ff0000)"

[fill]
symbol = " "

[time]
disabled = false
format = "[$time]($style) "
style = "dimmed gray"
time_format = "%R"

[memory_usage]
disabled = false
format = "use [$symbol$ram]($style) "
symbol = " "
style = "dimmed"
threshold = 50

[status]
disabled = true

[docker_context]
symbol = " "

[python]
symbol = " "
style = "blold green"

[golang]
symbol = "ﳑ "

[php]
symbol = " "

[shell]
disabled = false
fish_indicator = "[](#3595ff)"

[kotlin]
kotlin_binary = "kotlin"

[git_branch]
always_show_remote = true
format = "on [$symbol$branch]($style) "
symbol = " "
style = "fg:#b2d500"

[git_status]
format    = "([$all_status$ahead_behind ]($style))"
ahead     = "⇡${count}"
diverged  = "⇕⇡${ahead_count},⇣${behind_count}"
behind    = "⇣${count}"
untracked = '\( $count\)'
modified  = '\( $count\)'
staged    = '\( $count\)'
renamed   = '\(A$count\)'
deleted   = '\(﫧$count\)'
stashed   = " "
style = "fg:#b2d500"

[git_metrics]
disabled = false
