format = """
$time\
$jobs\
$directory\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$kotlin\
$lua\
$nodejs\
$php\
$python\
$rust\
$scala\
$swift\
$terraform\
$memory_usage\
$aws\
$gcloud\
$openstach\
$env_var\
$custom\
$cmd_duration\
$git_branch\
$git_status\
$git_commit\
$git_state\
$line_break\
$status\
$shell\
$character"""

scan_timeout = 30
command_timeout = 1500

[character]
success_symbol = " "
error_symbol = "[ ](#ff0000)"

[time]
disabled = false
format = "[$time]($style) "
style = "dimmed gray"
time_format = "%R"

[memory_usage]
disabled = false
format = "[$symbol$ram]($style) "
symbol = " "
style = "dimmed"
threshold = 50

[status]
disabled = false

[git_branch]
always_show_remote = true
format = "\n[$symbol$branch]($style) "
symbol = " "
style = "fg:#b2d500"

[git_status]
format    = "([\\[ $all_status$ahead_behind\\] ]($style))"
ahead     = "⇡${count} "
diverged  = "⇕⇡${ahead_count},⇣${behind_count} "
behind    = "⇣${count} "
untracked = " "
modified  = " "
staged    = " "
renamed   = "A"
deleted   = "﫧"
stashed   = " "

[docker_context]
symbol = " "

[python]
symbol = " "
style = "blold green"

[golang]
symbol = "ﳑ "

[php]
symbol = " "

[shell]
disabled = false
fish_indicator = "[](#3595ff)"

[kotlin]
kotlin_binary = "kotlin"
