format = """
$time\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nodejs\
$ocaml\
$php\
$python\
$rust\
$scala\
$swift\
$terraform\
$memory_usage\
$aws\
$gcloud\
$cmd_duration\
$line_break\
$character"""

scan_timeout = 10

[character]
success_symbol = "[]($style)"
error_symbol = "[]($style)"

[time]
disabled = false
format = "🕰  [$time]($style) "
style = "dimmed gray"
time_format = "%R"

[memory_usage]
disabled = false
format = "$symbol[$ram]($style) "
symbol = "[]($style) "
style = "dimmed"
threshold = 50

[status]
disabled = false

[git_branch]
symbol = "🌱 "

[docker_context]
symbol = " "

[python]
symbol = " "
style = "blold green"

[golang]
symbol = "ﳑ "

[php]
symbol = " "
