format = """
$hostname\
$username\
$directory\
$git_branch\
$git_state\
$git_metrics\
$git_status
$character
"""
add_newline = false

scan_timeout    = 30
command_timeout = 100

[cmd_duration]
disabled = true

[hostname]
ssh_only = false
disabled = true
style    = "bold fg:17"
format   = "[💻 $hostname ]($style)"
trim_at  = ".local"

[username]
# style_user  = "bold fg:17"
# format      = "[👤 $user ]($style)"
show_always = true

[directory]
# style             = "bold fg:17"
# format            = "[📂 $path ]($style)[$read_only]($read_only_style)"
# truncation_length = 2
# truncation_symbol = "…/"
# truncate_to_repo  = false

[character]
success_symbol = "[ ](green)"
error_symbol   = "[ ](#ff0000)"

[fill]
symbol = " "

[time]
disabled    = true
format      = "[$time]($style) "
style       = "dimmed gray"
time_format = "%R"

[memory_usage]
disabled  = true
format    = "use [$symbol$ram]($style) "
symbol    = " "
style     = "dimmed"
threshold = 50

[status]
disabled = true

[git_branch]
style  = "bold fg:16 bg:183"
symbol = " "
format = "[$symbol$branch(->origin/$remote_branch) ]($style)"

[git_status]
format    = "([$all_status$ahead_behind ]($style))"
ahead     = "⇡${count}"
diverged  = "⇕⇡${ahead_count}⇣${behind_count}"
behind    = "⇣$count"
untracked = ' $count '
modified  = ' $count '
staged    = ' $count '
renamed   = 'A$count '
deleted   = '﫧$count '
stashed   = ' $count '
style     = 'bold fg:16 bg:183'
