format = "$all"
# format = "$java"
# format = "$git_commit"

# scan_timeout = 30
# command_timeout = 500

[cmd_duration]
disabled = true

[character]
success_symbol = " "
error_symbol = "[ ](#ff0000)"

[fill]
symbol = " "

[time]
disabled = true
format = "[$time]($style) "
style = "dimmed gray"
time_format = "%R"

[memory_usage]
disabled = true
format = "use [$symbol$ram]($style) "
symbol = " "
style = "dimmed"
threshold = 50

[status]
disabled = true

[python]
version_format = ""
symbol = " "
style = "blold green"
[golang]
version_format = ""
symbol = "ﳑ "
[kotlin]
version_format = ""
kotlin_binary = "kotlin"
[java]
version_format = ""
[php]
version_format = ""
symbol = " "

[shell]
disabled = true
fish_indicator = "[](#3595ff)"

[git_branch]
always_show_remote = true
format = "on [$symbol$branch]($style) "
symbol = " "
style = "fg:#b2d500"

[git_status]
format = "([$all_status$ahead_behind ]($style))"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count},⇣${behind_count}"
behind = "⇣${count}"
untracked = '\( $count\)'
modified = '\( $count\)'
staged = '\( $count\)'
renamed = '\(A$count\)'
deleted = '\(﫧$count\)'
stashed = " "
style = "fg:#b2d500"

[git_commit]
commit_hash_length = 8
tag_symbol = "🔖 "
style = "bold yellow"
