[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'dense-analysis/ale'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'tpope/vim-commentary'
[[plugins]]
repo = 'plasticboy/vim-markdown'
