[[plugins]]
repo = 'Shougo/dein.vim'
# super completion using LSP like VSCode
[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
# colorful parentheses
[[plugins]]
repo = 'kien/rainbow_parentheses.vim'
# directory tree
[[plugins]]
repo = 'scrooloose/nerdtree'
# asynchronos linting
[[plugins]]
repo = 'dense-analysis/ale'
# useful status line
#[[plugins]]
#repo = 'vim-airline/vim-airline'
#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
# useful commentin/out
[[plugins]]
repo = 'preservim/nerdcommenter'
[[plugins]]
repo = 'plasticboy/vim-markdown'
# coooool color scheme
[[plugins]]
repo = 'morhetz/gruvbox'
# git in vim
[[plugins]]
repo = 'tpope/vim-fugitive'
# colored indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
# cooporation vim & tmux
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
# toml highlighting
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'posva/vim-vue'
# elixir highlighting
[[plugins]]
repo = 'elixir-lang/vim-elixir'
# auto switch paste mode
[[plugins]]
repo = 'roxma/vim-paste-easy'
# insert semicolon or comma
[[plugins]]
repo = 'lfilho/cosco.vim'
[[plugins]]
repo = 'tpope/vim-repeat'
# show git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'
# fzf
[[plugins]]
repo = 'junegunn/fzf.vim'
[[plugins]]
repo = 'airblade/vim-rooter'
# ultimate snippet
# [[plugins]]
# repo = 'SirVer/ultisnips'
# [[plugins]]
# repo = 'honza/vim-snippets'
