[[plugins]]
repo = 'Shougo/dein.vim'

# help
# [[plugins]]
# repo = 'nanotee/nvim-lua-guide'
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
" let g:denops_server_addr = '127.0.0.1:32123'
" let g:denops#debug = 1
'''
# [[plugins]]
# repo = 'vim-denops/denops-shared-server.vim'
# hook_add = '''
# command! DenopsSharedServerInstall call denops_shared_server#install()
# command! DenopsSharedServerUninstall call denops_shared_server#uninstall()
# '''


## color scheme
# [[plugins]]
# repo = 'dracula/vim'
[[plugins]]
repo = 'pineapplegiant/spaceduck'
[[plugins]]
repo = 'folke/tokyonight.nvim'
# [[plugins]]
# repo = 'sainnhe/gruvbox-material'
[[plugins]]
repo = 'sainnhe/everforest'

## icon
# [[plugins]]
# repo = 'kyazdani42/nvim-web-devicons'

## which-key
[[plugins]]
repo = 'folke/which-key.nvim'

# [[plugins]]
# repo='thinca/vim-quickrun'
