[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'lewis6991/impatient.nvim'

## color scheme
# [[plugins]]
# repo = 'dracula/vim'
# [[plugins]]
# repo = 'pineapplegiant/spaceduck'
[[plugins]]
repo = 'folke/tokyonight.nvim'
# [[plugins]]
# repo = 'sainnhe/gruvbox-material'
# [[plugins]]
# repo = 'sainnhe/everforest'

## 通知
[[plugins]]
repo = 'rcarriga/nvim-notify'
hook_source = '''
lua require('custom.nvim-notify')
'''

## icon
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

## which-key
[[plugins]]
repo = 'folke/which-key.nvim'

# [[plugins]]
# repo='thinca/vim-quickrun'

# [[plugins]]
# repo = 'kien/rainbow_parentheses.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/rainbow_parentheses.vim
# '''

#[[plugins]]
#repo = 'roxma/vim-paste-easy'
