[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
source ~/.config/nvim/plugins/ddc.vim
'''

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'skanehira/denops-gh.vim'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/plugins/lightline.vim
'''
[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'

# comment
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
source ~/.config/nvim/plugins/caw.vim
'''

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'roxma/vim-paste-easy'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/nvim/plugins/gitgutter.vim
'''

[[plugins]]
repo = 'cohama/lexima.vim'

# todo telescopeに変えるかどうか迷う
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0
[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'liuchengxu/vim-which-key'
hook_add = '''
source ~/.config/nvim/plugins/vim-which-key.vim
'''

[[plugins]]
repo='editorconfig/editorconfig-vim'

[[plugins]]
repo='dag/vim-fish'
hook_add='''
source ~/.config/nvim/plugins/fish.vim
'''
on_ft = [ "fish" ]

# ^vg_や0v$hで指定するテキスト範囲をもっと簡単に選択できるようにする
# val: 改行を含まずに一行まるごと選択
# vil: 両端の空白を除いた一行まるごと選択
[[plugins]]
repo='kana/vim-textobj-line'
depends=['vim-textobj-user']

[[plugins]]
repo='kana/vim-textobj-user'

[[plugins]]
repo = 'tpope/vim-surround'

# [[plugins]]
# repo = 'mattn/emmet-vim'
# on_fr = [ "html" ]

# [[plugins]]
# repo = 'udalov/kotlin-vim'
# on_ft = [ "kotlin" ]

# [[plugins]]
# repo = 'junegunn/vim-emoji'
# [[plugins]]
# repo = 'Kachyz/vim-gitmoji'
# hook_add='''
# set completefunc=emoji#complete
# '''

# [[plugins]]
# repo = 'tyru/eskk.vim'

# [[plugins]]
# repo = 'kien/rainbow_parentheses.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/rainbow_parentheses.vim
# '''

# [[plugins]]
# repo = 'elixir-lang/vim-elixir'
# on_ft = ['elixir']

# [[plugins]]
# repo = 'posva/vim-vue'
# on_ft = ['vue', 'js', 'md']
