[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'lewis6991/impatient.nvim'

# help
# [[plugins]]
# repo = 'nanotee/nvim-lua-guide'
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
" let g:denops_server_addr = '127.0.0.1:32123'
" let g:denops#debug = 1
'''
# [[plugins]]
# repo = 'vim-denops/denops-shared-server.vim'
# hook_add = '''
# command! DenopsSharedServerInstall call denops_shared_server#install()
# command! DenopsSharedServerUninstall call denops_shared_server#uninstall()
# '''

[[plugins]]
repo    = 'lambdalisue/guise.vim'
depends = ['denops.vim']

# syntax hilight
# NOTE: treesitterでは不都合な場合に利用する
[[plugins]]
repo = 'dag/vim-fish'
# NOTE: treesitterを使うとdein系のtomlのハイライトが上手くいかない
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'terrastruct/d2-vim'

## color scheme
[[plugins]]
repo = 'dracula/vim'
[[plugins]]
repo = 'pineapplegiant/spaceduck'
[[plugins]]
repo = 'folke/tokyonight.nvim'
[[plugins]]
repo = 'sainnhe/gruvbox-material'
[[plugins]]
repo = 'sainnhe/everforest'

## which-key
[[plugins]]
repo = 'folke/which-key.nvim'

# [[plugins]]
# repo='thinca/vim-quickrun'
