[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
" let g:denops_server_addr = '127.0.0.1:32123'
" let g:denops#debug = 1
'''
# [[plugins]]
# repo = 'vim-denops/denops-shared-server.vim'
# hook_add = '''
# command! DenopsSharedServerInstall call denops_shared_server#install()
# command! DenopsSharedServerUninstall call denops_shared_server#uninstall()
# '''

[[plugins]]
repo = 'lambdalisue/guise.vim'
[[plugins]]
repo = 'rhysd/committia.vim'

## colorscheme
# [[plugins]]
# repo = 'dracula/vim'
# [[plugins]]
# repo = 'pineapplegiant/spaceduck'
# [[plugins]]
# repo = 'folke/tokyonight.nvim'
# [[plugins]]
# repo = 'Domeee/mosel.nvim'
# [[plugins]]
# repo = 'sainnhe/gruvbox-material'
[[plugins]]
repo = 'sainnhe/everforest'
