[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
"let g:denops_server_addr = '127.0.0.1:32123'
"let g:denops#debug = 1
'''
# [[plugins]]
# repo = 'vim-denops/denops-shared-server.vim'
# hook_add = '''
# command! DenopsSharedServerInstall call denops_shared_server#install()
# command! DenopsSharedServerUninstall call denops_shared_server#uninstall()
# '''

[[plugins]]
repo = 'lambdalisue/guise.vim'
[[plugins]]
repo = 'rhysd/committia.vim'

## colorscheme
# [[plugins]]
# repo = 'dracula/vim'
# hook_source = '''
# colorscheme dracula
# '''
# [[plugins]]
# repo = 'pineapplegiant/spaceduck'
# hook_source = '''
# colorscheme spaceduck
# '''
[[plugins]]
repo = 'folke/tokyonight.nvim'
# [[plugins]]
# repo = 'Domeee/mosel.nvim'
# [[plugins]]
# repo = 'sainnhe/gruvbox-material'
[[plugins]]
repo = 'sainnhe/everforest'
#hook_source = '''
#colorscheme everforest
#'''

[[plugins]]
repo = 'rebelot/heirline.nvim'
lua_source = '''
require('custom.heirline')
'''

[[plugins]]
repo = 'folke/which-key.nvim'
lua_source = '''
local wk = require('which-key')
wk.setup({
  plugins = {
    marks = false, -- shows a list of your marks on ' and `
    registers = true, -- shows your registers on " in NORMAL or <C-r> in INSERT mode
    spelling = {
      enabled = false, -- enabling this will show WhichKey when pressing z= to select spelling suggestions
      suggestions = 20, -- how many suggestions should be shown in the list?
    },
    presets = {
      operators = false, -- adds help for operators like d, y, ... and registers them for motion / text object completion
      motions = false, -- adds help for motions
      text_objects = false, -- help for text objects triggered after entering an operator
      windows = false, -- default bindings on <c-w>
      nav = false, -- misc bindings to work with windows
      z = false, -- bindings for folds, spelling and others prefixed with z
      g = false, -- bindings for prefixed with g
    },
  },
})
wk.register({
  ['<Leader>'] = {
    f = {
      name = "+find"
    },
    g = {
      name = "+gtd"
    },
    t = {
      name = "+task"
    },
  }
})
'''
