## popup completion menu
[[plugins]]
repo = 'Shougo/pum.vim'
[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['pum.vim']
hook_post_source = '''
call popup_preview#enable()
'''

## ddc
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['context_filetype.vim', 'denops.vim', 'pum.vim', 'nvim-lspconfig']
on_event = ['InsertEnter']
hook_source = '''
lua require('custom.ddc')
'''

## ddc-source
## 
[[plugins]]
repo      = 'Shougo/ddc-around'
on_source = 'ddc.vim'
[[plugins]]
repo      = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'
[[plugins]]
repo      = 'Shougo/ddc-rg'
on_source = 'ddc.vim'
[[plugins]]
repo      = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'
[[plugins]]
repo      = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'
[[plugins]]
repo      = 'Shougo/neco-vim' # vim source
on_source = 'ddc.vim'

## ddc-filter
[[plugins]]
repo      = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'
[[plugins]]
repo      = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'
[[plugins]]
repo      = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'
[[plugins]]
repo      = 'Shougo/ddc-matcher_length'
on_source = 'ddc.vim'
[[plugins]]
repo      = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

## util
### kind label
[[plugins]]
repo      = 'mortepau/codicons.nvim'
on_source = 'ddc.vim'
### snippet
[[plugins]]
repo      = 'hrsh7th/vim-vsnip'
on_source = 'ddc.vim'
[[plugins]]
repo      = 'hrsh7th/vim-vsnip-integ'
on_source = 'ddc.vim'

## skk
[[plugins]]
repo = 'vim-skk/skkeleton'
# on_map = { i = '<Plug>(skkeleton-toggle)' }
on_event = ['InsertEnter']
depends = ['ddc.vim']
hook_add = '''
imap <C-h> <Plug>(skkeleton-toggle)
'''
hook_source = '''
autocmd User skkeleton-initialize-pre call s:skkeleton_init()
function! s:skkeleton_init() abort
  call skkeleton#config({
    \ 'globalJisyo': '~/.config/SKK-JISYO.L',
    \ 'eggLikeNewline': v:true,
    \ 'registerConvertResult': v:true,
    \ })
  call skkeleton#config({
    \   'markerHenkan': '<>',
    \   'markerHenkanSelect': '>>',
    \ })
  call skkeleton#register_kanatable('rom', {
    \ 'jj': 'escape',
    \ '~': ['〜', ''],
    \ "z\<Space>": ["\u3000", ''],
    \ })
endfunction

autocmd User skkeleton-enable-pre call s:skkeleton_pre()
function! s:skkeleton_pre() abort
  let s:prev_buffer_config = ddc#custom#get_buffer()
  call ddc#custom#patch_buffer('sources', ['skkeleton'])
  iunmap <Esc>
endfunction

autocmd User skkeleton-disable-pre call s:skkeleton_post()
function! s:skkeleton_post() abort
  " Restore sources
  call ddc#custom#set_buffer(s:prev_buffer_config)
  inoremap <silent><expr> <Esc>  ddc#map#pum_visible() ? '<Cmd>call pum#map#cancel()<CR><Esc>' : '<Esc>'
  "inoremap <silent><expr> <CR> ddc#map#pum_visible() ? '<Cmd>call pum#map#confirm()<CR>' : '<CR>'
endfunction
'''
