[[plugins]]
repo = 'lambdalisue/fern.vim'
on_cmd = 'Fern'
hook_add = '''
let g:fern#disable_default_mappings = 1
let g:fern#default_exclude = '\.git'
'''
hook_source = '''
call fern_git_status#init()
'''
[plugins.ftplugin]
fern = '''
call glyph_palette#apply()
nmap <silent><buffer> p <Plug>(fern-action-preview:toggle)
nmap <buffer> ? <Plug>(fern-action-help)
nmap <buffer> . <Plug>(fern-action-hidden:toggle)
nmap <buffer> m <Plug>(fern-action-mark:toggle)
nmap <buffer><expr>
  \ <Plug>(fern-my-open-or-expand-or-collapse)
  \ fern#smart#leaf(
  \   '<Plug>(fern-action-open)',
  \   '<Plug>(fern-action-expand:stay)',
  \   '<Plug>(fern-action-collapse)',
  \ )
nmap <buffer><nowait> <Return> <Plug>(fern-my-open-or-expand-or-collapse)
nmap <buffer> oj <Plug>(fern-action-open:bellow)
nmap <buffer> ok <Plug>(fern-action-open:above)
nmap <buffer> ol <Plug>(fern-action-open:right)
nmap <buffer> oh <Plug>(fern-action-open:left)
nmap <buffer> n <Plug>(fern-action-new-file)
nmap <buffer> D <Plug>(fern-action-new-dir)
nmap <buffer> M <Plug>(fern-action-move)
nmap <buffer> d <Plug>(fern-action-trash)
nmap <buffer> r <Plug>(fern-action-rename)
" nmap <buffer> q <Plug>(fern-action-cancel)
" nmap <buffer>  <Plug>(fern-action-focus:parent)
'''
[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'
on_source = 'fern.vim'
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = 'fern.vim'
[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
on_source = 'fern.vim'
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
on_source = 'fern.vim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
on_source = 'fern.vim'
hook_source = '''
let g:fern#renderer = "nerdfont"
'''
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
on_source = 'fern.vim'
