[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_source = '''
let g:context_filetype#ignore_patterns = {
    \ 'toml': ['^\s*#\s*'],
    \ }
'''
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'lfilho/cosco.vim'
on_ft = ['php', 'rust', 'java', 'dart']
hook_source = '''
source ~/.config/nvim/plugins/cosco.vim
'''

## pum
[[plugins]]
repo = 'Shougo/pum.vim'
[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['pum.vim']

## ddc
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['context_filetype.vim', 'denops.vim', 'pum.vim']
on_event = 'InsertEnter'
hook_source = '''
lua << EOF
require('custom.ddc')
EOF
'''
[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'
[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'
[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'
[[plugins]]
repo = 'tani/ddc-git'
on_source = 'ddc.vim'
