enable_passive: true
passive_key: SHIFT
secure_input_notification: false

global_vars:
  - name: "first_name"
    type: "dummy"
    params:
      echo: "一瀬"
  - name: "last_name"
    type: "dummy"
    params:
      echo: "喜弘"
  - name: "clipboard"
    type: "clipboard"

matches:
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ";name"
    replace: "{{first_name}} {{last_name}}"
  - trigger: ";fname"
    replace: "{{first_name}}"
  - trigger: ";lname"
    replace: "{{last_name}}"

  - trigger: ";tester_info"
    replace: |
      端末: Pixel3
      Version: Android11
      AppVersion: 0.6.7
      実施者: 一瀬

  - trigger: ";pmail"
    replace: "maruisangmai@gmail.com"
  - trigger: ";cmail"
    replace: "mikan.ichinose@karabiner.tech"

  # image tag
  - trigger: ";img"
    replace: |
      <img 
        src="{{clipboard}}"
        width="500"/>
