[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
let g:everforest_background = 'hard'
let g:everforest_better_performance = 1
autocmd MikanAutoCmd VimEnter,BufRead * ++once
        \ colorscheme everforest
        \ | highlight Normal guibg=NONE
        \ | highlight NormalNC guibg=NONE
'''
