[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
on_map = { ict = '<Plug>(skkeleton-toggle)' }
on_event = ['CursorHold']
hooks_file = '$BASE_DIR/plugins/skkeleton.vim'

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
#depends = 'denops.vim'
#denops_wait = false

