[[plugins]]
repo = 'Shougo/dpp.vim'
hooks_file = '$BASE_DIR/plugins/dpp.vim'

# extension
[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
on_source = 'dpp.vim'
[[plugins]]
repo = 'Shougo/dpp-ext-toml'
on_source = 'dpp.vim'
hook_add = '''
autocmd MikanAutoCmd BufRead */rc/*.toml ++once call dpp#ext#toml#syntax()
'''
[[plugins]]
repo = 'Shougo/dpp-ext-local'
on_source = 'dpp.vim'
[[plugins]]
repo = 'Shougo/dpp-ext-installer'
on_source = 'dpp.vim'

# protocol
[[plugins]]
repo = 'Shougo/dpp-protocol-git'
on_source = 'dpp.vim'
