[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = ['BufRead']
hook_source = '''
lua require('custom.lsp')
lua vim.notify('onSource nvim-lspconfig')
'''

[[plugins]]
repo      = 'williamboman/mason.nvim'
on_source = ['nvim-lspconfig']
[[plugins]]
repo      = 'williamboman/mason-lspconfig.nvim'
on_source = ['nvim-lspconfig']
depends   = ['mason.nvim']
[[plugins]]
repo      = 'WhoIsSethDaniel/mason-tool-installer.nvim'
on_source = ['nvim-lspconfig']
depends   = ['mason.nvim']
## lua development
[[plugins]]
repo      = 'folke/lua-dev.nvim'
on_source = ['nvim-lspconfig']
[[plugins]]
repo      = 'lukas-reineke/lsp-format.nvim'
on_source = ['nvim-lspconfig', 'null-ls']
[[plugins]]
repo      = 'b0o/SchemaStore.nvim'
on_source = ['nvim-lspconfig']
[[plugins]]
repo   = 'weilbith/nvim-code-action-menu'
on_cmd = 'CodeActionMemu'
[[plugins]]
repo = "j-hui/fidget.nvim"
on_source = ['nvim-lspconfig']
hook_source = '''
lua require('fidget').setup()
'''
[[plugins]]
repo      = 'mortepau/codicons.nvim'
on_source = 'nvim-lspconfig'
[[plugins]]
repo = 'onsails/lspkind.nvim'
on_source = 'nvim-lspconfig'
hook_source = '''
lua << EOF
require('lspkind').init {
  mode = 'symbol',
  preset = 'codicons',
}
EOF
'''
# [[plugins]]
# repo = 'nvim-lua/lsp-status.nvim'
# depends = ['nvim-lspconfig']
# on_event = 'BufRead'
# hook_source = '''
# lua << EOF
# require('lsp-status').register_progress()
# EOF
# '''
## general language server
[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = ['nvim-lspconfig']
on_event = ['BufRead']
hook_source = '''
lua require('custom.null-ls')
'''
## virtual-line
[[plugins]]
repo = 'https://git.sr.ht/~whynothugo/lsp_lines.nvim'
on_source = 'nvim-lspconfig'
hook_source = '''
lua require('custom.lsp_lines')
'''
[[plugins]]
repo = 'folke/lsp-colors.nvim'
on_source = 'nvim-lspconfig'
hook_source = '''
lua require("lsp-colors").setup()
'''
[[plugins]]
repo      = 'SmiteshP/nvim-navic'
on_source = 'nvim-lspconfig'
