[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_event = 'VimEnter'
depends = ['plenary.nvim', 'nvim-lspconfig']
hook_source = '''
lua <<EOF
require('custom.telescope')
local wk = require('which-key')
wk.register({
  ['<Leader>'] = {
    t = {
      name = '+telescope',
      f = {'<cmd>Telescope find_files<cr>', 'find file'},
      -- b = {'<cmd>Ddu -name=buffers buffer<cr>', 'find buffer'},
      -- r = {'<cmd>Ddu -name=search rg -source-param-input=`input(\'Pattern: \')`<cr>', 'find source'},
      -- d = {'<cmd>Ddu -name=dein dein<cr>', 'dein'},
      -- h = {'<cmd>Ddu -name=help help<cr>', 'find help'},
      -- m = {'<cmd>Ddu -name=mr mr<cr>', 'find mr'},
      -- c = {'<cmd>Ddu -name=commands command_history -ui-param-startFilter<cr>', 'find command'},
      C = {'<cmd>Telescope colorscheme<cr>', 'find color'},
    },
  }
})
EOF
'''
[[plugins]]
repo      = 'nvim-telescope/telescope-fzf-native.nvim'
on_source = 'telescope.nvim'
build     = 'make'
[[plugins]]
repo      = 'nvim-telescope/telescope-project.nvim'
on_source = 'telescope.nvim'
[[plugins]]
repo      = 'nvim-telescope/telescope-file-browser.nvim'
on_source = 'telescope.nvim'
