[misc]
# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
disable = [
  "containers",
  "emacs",
  "vim",
  "pip3",
  "flutter",
  "nix",
  "julia",
  "node",
  "yarn",
  "pnpm",
  # "git_repos",
  # "mas",
  "system",
]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Display the time in step titles
display_time = true

# Cleanup temporary or old files
cleanup = true

[git]
max_concurrency = 5
repos = [
  "~/ghq/**/",
  "~/ghq-karabiner/**/",
]
# Don't pull the predefined git repos
pull_predefined = false
# Arguments to pass Git when pulling Repositories
arguments = "--rebase --autostash"

# Commands to run before anything
[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
#"Python Environment" = "~/dev/.env/bin/pip install -i https://pypi.python.org/simple -U --upgrade-strategy eager jupyter"

[brew]
greedy_cask = true
