name: lint

on:
  push:
    branches:
      - master

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
